console.log("What results in Boolean ?");
console.log("Boolean experession and Logical operators are result in it.");
console.log("Some logical operators in Boolean are:");
console.log("'&&': and");
console.log("'||': or");
console.log("'!': not");
console.log("'^': exclusive or");
console.log("Some comparision operators in Boolean are:");
console.log("'<': less than");
console.log("'<=': less than or equal to");
console.log("'==': equal to");
console.log("'!'=: not equal to");
console.log("'>=': greater than or equal to");
console.log("'>': greater than");